spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_help?characterEcoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: MQTG123123

    druid:
      aop-patterns: cn.hanamizu.*
      filters: stat,wall

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin

      web-stat-filter:
        enabled: true
        url-pattern: /*
logging:
  level:
    cn.hanamizu.campushelp.mapper: debug
cos:
  secretId: your-secret-id
  secretKey: your-secret-key
  region: ap-shanghai

