spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_help?characterEcoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: MQTG123123

    druid:
      aop-patterns: cn.hanamizu.*
      filters: stat,wall

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin

      web-stat-filter:
        enabled: true
        url-pattern: /*
logging:
  level:
    cn.hanamizu.campushelp.mapper: debug

